### PR TITLE
A nip for POW for events

### PR DESCRIPTION
**Pull request by cerbwm**

### CODE REVIEW

**Comment by scsibug** [comment]
Distinct points/suggestions in each paragraph:

I think the goal of this is both to "draw attention to", and "provide denial of service resistance", and that should probably be called out in the intro.

We should have at least one explicit example of how a PoW algorithm name is formed, at least to provide a default.  If you can proceed with the `pow` being described in a two-element string array, as described in the `POW Vote Events` section, I think you should mirror that _exactly_ in the `pow` field.

I like having a mechanism to embed PoW directly in the event, as well as allowing 3rd parties (including relays) to provide PoW through separate events.  This points to two `pow` varieties, "unsigned / anonymous" and "signed / attributed".

I do not think the Relay Usage section is as clear as it could be.  Perhaps instead; "Relays MAY choose to store a single `pow` value for an event, representing the largest work value, and include with subsequent messages to clients."  It should probably also be mentioned that relays can update the stored `pow` value for any other event that comes in with a greater value than what they have stored already (since they are discarding kind=6 events, the best way to propagate the pow is on the events they distribute to clients).  Basically, if a relay sees a duplicate event with a greater PoW, it could still choose to update `pow`.  It does not need to only do this for kind=6 "signed" PoW.

A big downside with this general approach is that it does not provide a great mechanism for combining PoW performed by multiple parties (so 10 upvoters with difficulty 3 would be erased by a single upvote of difficult 4).  I think this is so distinct from what people expect from "upvotes" that we would need an entirely different phrase to describe it.  I don't have a solution to the problem though.  In practice a client will see a random mix of the relay-provided/anonymous `pow` field showing the single-greatest-pow, and potentially a stream of kind=6 signed upvotes from people, all with varying amounts of `pow`.  I guess it is on clients to determine how to provide this (complex) information to the end-user.

I do not follow at all the final paragraph about advertising identity.  I would need to see a very specific example to understand what is being proposed there.

Relays probably should be discouraged from throwing away kind=6 events ("MAY" works either way here).  Perhaps it is more important to say something like "Relays MAY discard events of kind=6 that in their view do not represent sufficiently large amounts of work".  Again, this provides anti-spam; no sense in storing PoW that represents 1000 CPU cycles but takes 400 bytes of storage.

Final thoughts:  
* I like that relays can use the best `pow` dynamically over time, and that clients can get this "best PoW" with no extra work/queries.
* I like user-signed `pow` as a separate kind, so it can be queried or not, and it provides an additional signal as to which authors/events are legit.
* I think the `pow` format should be rigidly defined as a two-element string array, both on the field and in the content body.
* I think at least one algorithm should be proposed and included in the NIP.

**Comment by cerbwm** [comment]
Please see the latest commit where I tried to address your comments:
https://github.com/fiatjaf/nostr/pull/56/commits/e1dc71477c3bebe74b98567725e3d26a13055e79

I think the original document did a bad job of explaining that kind `6` events cannot function as a reliable user-signed POW since the POW is for the referred event not for the kind `6` event.  That is what the final paragraph tried to address and I hope my edits make this more clear.

**Review by namklabs — COMMENTED** [review]
So is the POW _based_ on cuckoo-cycle or _IS_ it cuckoo-cycle? I think it would be good to clarify this.

Also, I think you should clarify that it is up to the user to implement cuckoo-cycle and provide some resources to assist in doing this so that people are more likely to do so.

I understand why you referenced BIP154 but it would be very helpful to provide other additional resources.

For instance, https://github.com/handshake-org/bcuckoo is a pure JS implementation of cuckoo-cycle in 679 lines. This would be way easier to use than trying to sift through https://github.com/tromp/cuckoo, especially if you're looking at implementing POW in JavaScript.

```Suggestion
A user may want to call attention to an event by
including proof of work (POW) with the event.
Similarly, to limit the number of events,
a relay may require that each event come with a certain amount of POW.

Clients may implement the cuckoo-cycle algorithm
to create POW for an event. The Cuckoo-cycle
algorithm is defined in [BIP154](https://bips.xyz/154#cuckoo-cycle-1).
Many implementations can be found in various languages:

- JavaScript: https://github.com/handshake-org/bcuckoo
- C++: https://github.com/tromp/cuckoo
```

**Comment by vinliao** [comment]
Two cents: The main purpose of POW is to prevent spam - without it, anyone can jam the chain with their blocks to claim the block reward. Proof-of-Work is useful for a globally-distributed database where anyone can submit a block, but I think Nostr relay is different. Nostr relay is more akin to an isolated island where you, as the relay owner, set the rule of the island. A way to effectively prevent spam is hosting a private relay with a whitelist on it. Setting a subscription fee to use a public relay is another way; creating an event-per-hour-per-pubkey limit is another way.

**Comment by cerbwm** [comment]
> So is the POW _based_ on cuckoo-cycle or _IS_ it cuckoo-cycle? I think it would be good to clarify this.
> 
> Also, I think you should clarify that it is up to the user to implement cuckoo-cycle and provide some resources to assist in doing this so that people are more likely to do so.
> 
> I understand why you referenced BIP154 but it would be very helpful to provide other additional resources.
> 
> For instance, https://github.com/handshake-org/bcuckoo is a pure JS implementation of cuckoo-cycle in 679 lines. This would be way easier to use than trying to sift through https://github.com/tromp/cuckoo, especially if you're looking at implementing POW in JavaScript.
> 
> ```
> A user may want to call attention to an event by
> including proof of work (POW) with the event.
> Similarly, to limit the number of events,
> a relay may require that each event come with a certain amount of POW.
> 
> Clients may implement the cuckoo-cycle algorithm
> to create POW for an event. The Cuckoo-cycle
> algorithm is defined in [BIP154](https://bips.xyz/154#cuckoo-cycle-1).
> Many implementations can be found in various languages:
> 
> - JavaScript: https://github.com/handshake-org/bcuckoo
> - C++: https://github.com/tromp/cuckoo
> ```

Thank you for your comments.  Absolutely agree, still working on this, ill make a new PR when finished!

**Comment by cerbwm** [comment]
> Two cents: The main purpose of POW is to prevent spam - without it, anyone can jam the chain with their blocks to claim the block reward. Proof-of-Work is useful for a globally-distributed database where anyone can submit a block, but I think Nostr relay is different. Nostr relay is more akin to an isolated island where you, as the relay owner, set the rule of the island. A way to effectively prevent spam is hosting a private relay with a whitelist on it. Setting a subscription fee to use a public relay is another way; creating an event-per-hour-per-pubkey limit is another way.

Yes, I understand your point.
I disagree though, I think the potential of POW is much greater than spam prevention (see for example https://nakamotoinstitute.org/mempool/the-proof-of-work-concept/).

**Comment by vinliao** [comment]
Maybe I'm missing something. Can you give me a specific example on what a POW-enabled Nostr can do that non-POW Nostr can't? (Bitmessage seems to be NIP-04 combined with POW. Interesting.)

**Comment by cerbwm** [comment]
Yes, bitmessage uses POW for spam prevention.  My pet use case will be verifiable up-votes for content discovery.

I think that Daniel Krawisz's big idea is that POW is a general solution to the coordination problem.  A universal POW message board gives everyone a way to peek outside of their trusted peer echo chambers and see what everyone else is thinking.  Prevents algorithmic manipulation of sense making.  Very important for this POW message board to be censorship resistant, hence nostr.

**Pull request closed without merging**
