### PR TITLE
Added advanced_note

### PR DESCRIPTION
**Pull request by arcbtc**
Includes text, image, timestamp

### CODE REVIEW

**Comment by arcbtc** [comment]
Sorry, timestamp not needed

**Comment by fiatjaf** [comment]
What if you just included an URL in the text note and the client decided to display that in the best possible manner? Twitter does something like this, actually. Embedded pictures and video are just URLs in the the tweet note.

**Comment by fiatjaf** [comment]
Although I don't know if this will work on a purely web-based client (but maybe it will), something like this library can be used if the client is installed or a browser extension: https://github.com/feross/render-media

It supports images, video, audio, pdf, zipfiles, txt, svg, rss, json, yaml, word and openoffice formats, xls, html, among others.

**Comment by arcbtc** [comment]
Thats not very decentralised :/

**Comment by arcbtc** [comment]
Just allow small images, you allow them for profile pictures
This is also needed for marketplace applications
Allowing other relays to handle such data, doesn't mean your relay has to handle it

**Comment by fiatjaf** [comment]
I'm not disallowing anything, you're free to do it, I'm saying that this doesn't look like a good addition because it creates a whole new event kind that has to be handled differently by clients for a very small tweak.

I see two better options:

1. Make it a whole new event, a `media` event or something, but then make it more general: allow video, image, audio or I don't know what other kind of thing to be set, and perhaps specify the mimetype of the media so it's easier for clients to know how to display it. Or better than this: make a more generic `mediagroup` event type that allows people to include multiple media items along with a text. That's certainly a necessary thing.
2. Do as say for now and don't add new types, just display textnotes that contain links to images differently (search URLs ending in jpg/png in the textnote and display them differently). As we accumulate more experience we add more event kinds to the spec.

**Comment by fiatjaf** [comment]
Also for Diagon Alley we need a new event kind completely, let's not fill event kinds intended for text notes with weird shop data.

It will use a ton of different structured data. Let's open a NIP for it once we start working on it and finding out what kind of data it will need. Then we can probably assign event kinds `254` and `255` to it and it could contain something like

```json
// 254: diagon-alley stand metadata
{
  "name": "Tom's Cheese Shop",
  "address": "Bitcoin St. 542, Bitcoin City",
  ...
}
```

```json
// 255: diagon-alley stand offer
{
  "name": "Cheese",
  "price": 2999,
  "picture": "https://pic.com/pic.png"
  ...
}
```

**Comment by arcbtc** [comment]
Will start a better proposal at a later date

**Comment by earonesty** [comment]
personally, i think it's ok/good to NOT support tagged/xml/html styled posts.  twitter's success was, in part, because of its limitations.   we're not trying to replace html/css!   nostr already supports threads, and threads can be rolled up.   so no need to have multiple images in a post, for example.   can stick with one image, one text string.

```
{"type": "text/nostr-json", "message": "this message contains an image", "image": {"type": "image/jpg", "data": "b64-image-data"}}
```

**Comment by earonesty** [comment]
@fiatjaf i think this proposal is fine.   urls can already include embedded mime types and data.   can change the name "image" to "url" so it's not specific as to what the url is.

**Pull request closed without merging**
